name: Sync Patreon Codes

on:
  push:
    paths:
      - 'data/pending/*.json'

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Patreon Sync
        env:
          PATREON_ID: ${{ secrets.PATREON_ID }}
          PATREON_SECRET: ${{ secrets.PATREON_SECRET }}
        run: node .github/scripts/patreon-sync.js

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/patreon.json
          git commit -m "Update patreon.json"
          git push
